# Generated by Django 4.1.6 on 2023-06-05 16:38

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import quotes.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('to_name', models.CharField(max_length=1000)),
                ('to_email', models.EmailField(max_length=1000)),
                ('to_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('to_street', models.CharField(max_length=1000)),
                ('to_city', models.CharField(max_length=1000)),
                ('to_state', models.CharField(max_length=1000)),
                ('to_zip', models.CharField(max_length=1000)),
                ('from_name', models.CharField(max_length=1000)),
                ('from_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('from_street', models.CharField(max_length=1000)),
                ('from_city', models.CharField(max_length=1000)),
                ('from_state', models.CharField(max_length=1000)),
                ('from_zip', models.CharField(max_length=1000)),
                ('refrence_number', models.CharField(blank=True, max_length=1000, null=True)),
                ('bill_to_name', models.CharField(max_length=1000)),
                ('bill_to_email', models.EmailField(max_length=1000)),
                ('bill_to_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('designer_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('designer_email', models.EmailField(blank=True, max_length=1000, null=True)),
                ('designer_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('delivery_type', models.CharField(max_length=1000)),
                ('delivery_notes', models.CharField(blank=True, max_length=1000, null=True)),
                ('delivery_options', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), blank=True, null=True, size=None)),
                ('encoding', models.CharField(blank=True, max_length=10, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuoteOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_description', models.CharField(max_length=1000)),
                ('option_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selected_option', models.BooleanField(default=False)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes.quote')),
            ],
        ),
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.FileField(blank=True, null=True, upload_to=quotes.models.quote_label_upload)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes.quote')),
            ],
        ),
    ]
