# Generated by Django 4.1.6 on 2023-06-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quote',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='paid_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('send_options_notification', 'Send Options Notification'), ('options_notification_sent', 'Options Notification Sent'), ('needs_payment', 'Needs Payment'), ('paid', 'Paid'), ('send_label_notification', 'Send Label Notification'), ('label_notification_sent', 'Label Notification Sent'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='created', max_length=25),
        ),
    ]
