# Generated by Django 4.1.6 on 2023-06-22 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_quote_paid_quote_paid_amount_quote_paid_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='refrence_number',
            new_name='delivery_window',
        ),
        migrations.AddField(
            model_name='quote',
            name='pickup_window',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='reference_number',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('send_options_notification', 'Send Options Notification'), ('options_notification_sent', 'Options Notification Sent'), ('needs_payment', 'Needs Payment'), ('resend_payment_notification', 'Resend Payment Notification'), ('paid', 'Paid'), ('send_label_notification', 'Send Label Notification'), ('label_notification_sent', 'Label Notification Sent'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='created', max_length=30),
        ),
    ]
