# Generated by Django 4.1.6 on 2023-06-28 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_rename_refrence_number_quote_delivery_window_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='from_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('send_created_notification', 'Send Created Notification'), ('created', 'Created'), ('send_options_notification', 'Send Options Notification'), ('options_notification_sent', 'Options Notification Sent'), ('needs_payment', 'Needs Payment'), ('resend_payment_notification', 'Resend Payment Notification'), ('paid', 'Paid'), ('send_label_notification', 'Send Label Notification'), ('label_notification_sent', 'Label Notification Sent'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='created', max_length=30),
        ),
    ]
