# Generated by Django 4.1.6 on 2023-06-28 02:22

from django.db import migrations, models
import django.db.models.deletion
import quotes.models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_quote_from_email_alter_quote_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteBol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bol', models.FileField(blank=True, null=True, upload_to=quotes.models.quote_label_upload)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes.quote')),
            ],
        ),
    ]
